# Generated by Django 5.2.4 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_analisis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ant', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pacientes',
            name='analisis_func',
            field=models.ManyToManyField(related_name='pacientes', to='pacientes.analisisfuncional'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='antecedentes',
            field=models.ManyToManyField(related_name='pacientes', to='pacientes.antecedentes'),
        ),
    ]
