# Generated by Django 5.2.4 on 2025-09-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_analisisfuncional_antecedentes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='analisis_func',
            new_name='analisis_funcional',
        ),
    ]
